In [119]:
import pandas as pd
import numpy as np

In [120]:
df = pd.read_csv("/content/independent-house.csv")

In [121]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [122]:
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [123]:
df.drop(columns = ('link'),inplace = True)

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   object
 1   society          471 non-null    object
 2   price            968 non-null    object
 3   rate             1054 non-null   object
 4   area             1095 non-null   object
 5   areaWithType     987 non-null    object
 6   bedRoom          987 non-null    object
 7   bathroom         987 non-null    object
 8   balcony          987 non-null    object
 9   additionalRoom   589 non-null    object
 10  address          1031 non-null   object
 11  noOfFloor        967 non-null    object
 12  facing           674 non-null    object
 13  agePossession    987 non-null    object
 14  nearbyLocations  913 non-null    object
 15  description      1036 non-null   object
 16  furnishDetails   743 non-null    object
 17  features         674 non-null    object
 18  rating           907 non-null    object
 19  property_id      1036 non-null   object
dtypes: object(20)
memory usage: 171.2+ KB

In [125]:
df = df[~df['price'].isna()]

In [126]:
df.isna().sum()

property_name        0
society            577
price                0
rate                10
area                 0
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom     391
address              5
noOfFloor           20
facing             307
agePossession        0
nearbyLocations    122
description          0
furnishDetails     239
features           309
rating             121
property_id          0
dtype: int64

In [127]:
df.head(3)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898

In [128]:
df.duplicated().sum()

np.int64(13)

In [129]:
df = df.drop_duplicates()

In [130]:
df['society']=df['society'].fillna('NA')

In [131]:
df['society'].replace('nul','NA')

0                                        Bptp Visionnaire
1                                                      NA
2                                                      NA
3                                                      NA
4                                                      NA
5                                                      NA
6                                      Emaar MGF Marbella
7                                  Luxury DLF City Floors
8                                                      NA
9                            Sushant Lok 1 Builder Floors
10                                                     NA
11                                                     NA
12                                 DLF City Plots Phase 3
13                                                     NA
14                                                     NA
15                                                     NA
16                                 DLF City Plots Phase 2
17                                                     NA
18                                         Unitech Espace
19                                                     NA
20                                                     NA
21                                     Emaar MGF Marbella
22                                                     NA
23                                     Vipul Tatvam Villa
24                                                     NA
25                           Ansal Sushant Lok Plots4.1 ★
26                                     Grover Homes Sec 4
27                                                     NA
28                                                     NA
29                                                     NA
30                                 Ansal API Esencia3.7 ★
31                                                     NA
32                                                     NA
33                                                     NA
34                                                     NA
35                                                     NA
36                              FLOOR WISE DESIGNER KOTHI
37                                                     NA
38                              Suncity Essel Towers4.2 ★
39                                                     NA
40                                                     NA
41                                              sector 37
42                                                     NA
43                                                     NA
44                                                     NA
45                                                     NA
46                                                     NA
48                                       Bptp Visionnaire
49                                                     NA
50                                                     NA
51                                                     NA
52                                                     NA
53                               Experion Windchants3.8 ★
54                                    Uppal Southend4.0 ★
55                                     Vipul Tatvam Villa
56                                     Vipul Tatvam Villa
57                                                     NA
58                              DLF New Town Heights3.7 ★
59                            DLF New Town Heights 24.0 ★
73                            Puri Diplomatic Greens4.0 ★
74                                                     NA
77                                                     NA
78                                                     NA
92                                                     NA
93                                                     NA
103                   International City by Sobha Phase 1
104                   International City by SOBHA Phase 2
114                                    Emaar MGF Marbella
119                                                    NA
120                                                    NA
121                                                    NA
122                                    Vipul Tatvam Villa
125                                                    NA
126                                                    NA
127                   International City by Sobha Phase 1
129                   International City by Sobha Phase 1
130                                                    NA
131                                                    NA
132                                    Vipul Tatvam Villa
133                                                    NA
134                                                    NA
135                                                    NA
136                                                    NA
137                                                    NA
138                                                    NA
139                                                    NA
140                                    Vipul Tatvam Villa
141                                    Emaar MGF Marbella
142                   International City by SOBHA Phase 2
143                   International City by SOBHA Phase 2
144                   International City by SOBHA Phase 2
145                   International City by SOBHA Phase 2
146                   International City by SOBHA Phase 2
147                                huda sector-56 gurgaon
148                                            Sector-17C
149                   International City by Sobha Phase 1
150                   International City by Sobha Phase 1
151                                      Bptp Visionnaire
152                                      Bptp Visionnaire
153                                                    NA
154                   International City by Sobha Phase 1
155                   International City by Sobha Phase 1
156                                                    NA
157                                                    NA
158                                                    NA
159                                                    NA
160                                                    NA
161                                                    NA
162                                                    NA
163                          Ansal Sushant Lok Plots4.1 ★
164                   International City by Sobha Phase 1
165                                                    NA
166                                         private house
167                                                    NA
168                                                    NA
169                                                    NA
170                                                    NA
171                                Unitech Deerwood Chase
172                                  Unitech Aspen Greens
173                                    Ansals Palam Vihar
174                   International City by SOBHA Phase 2
175                   International City by SOBHA Phase 2
176                                      Bptp Visionnaire
177                   International City by Sobha Phase 1
200                                                    NA
201                                                    NA
202                         HUDA Ashok Vihar Phase 13.9 ★
203                                                    NA
204                           Ashok Vihar Phase 3 Gurgaon
205                                                    NA
206                                                    NA
207                                                    NA
208                                                    NA
209                                          Farrukhnagar
210                                                    NA
211                                                    NA
212                                                    NA
213                                                    NA
214                                                    NA
215                                                    NA
216                                             Prem Kunj
217                                                    NA
218                                                    NA
219                                                    NA
220           secter 16a daultabad faridabad house no 313
221                                                    NA
222                                                    NA
223                                        DLF City Plots
224                                                    NA
225                                        Not Applicable
226                                                    NA
227                                                    NA
228                                                    NA
229                                                    NA
230                                                    NA
231                                                    NA
232                                                    NA
233                                                    NA
234                                  Housing Board Colony
235                                                    NA
236                                                    NA
237                                 rajendra park sec 105
238                                                    NA
239                                              shivpuri
240                                    Ansal Heights3.2 ★
241                                            Ninex City
242                                      Spaze Privy3.9 ★
243                                                    NA
244                            Signature Global Park4.0 ★
245                                                    NA
246                                               My Home
247                                                    NA
248                                   Surat nagar phase 2
249                                                    NA
250                              Unitech Uniworld Resorts
251                                                    NA
252                                                    NA
253                                DLF Gardencity Enclave
254                                                    NA
255                                 Rajendra Park Gurgaon
256                                                    NA
257                                                    NA
258                                                    NA
259                                                    NA
260                                                    NA
261                                     house number B-34
262                                                    NA
263                                                    NA
264                                                    NA
265                                                    NA
266                                                    NA
267                                                    NA
268                                                    NA
269                                                    NA
270                                                    NA
271                                                    NA
272                                                    NA
273                                                    NA
274                                   ATS Tourmaline3.9 ★
275                                                    NA
276                                                    NA
277                                       Bhawani enclave
278                                                    NA
279                                                    NA
280                                                    NA
281                                                    NA
282                                                    NA
283                                                    NA
284                                                    NA
286                                                    NA
287                                                    NA
288                                   Om Nagar, Sector-11
289                                                    NA
290                                                    NA
291                                                    NA
292                                                    NA
293                                                    NA
294                               Project Mianwali Colony
295                                                    NA
296                                                    NA
297                                                    NA
298                                                    NA
299                                                    NA
300                                                    NA
301                                                    NA
302                          Project Housing Board Colony
303                                        DLF The Arbour
304                                DLF Garden City Floors
305                                                    NA
306                                                    NA
307                                                    NA
309                                                    NA
310                                                    NA
311                                            Huda Plots
314                                                    NA
315                                                    NA
316                                                    NA
317                                          Malibu Towne
318                             Suncity Essel Towers4.2 ★
320                                                    NA
321                                  bhim nagar, sector 6
322                                                    NA
323                                                    NA
324                                       Anamika Enclave
325                                                    NA
326                                                    NA
332                                        Not Applicable
333                                                    NA
335                                                    NA
336                                                    NA
337                                                    NA
338                                                    NA
339                                                    NA
340                                                    NA
341                                                    NA
342                                                    NA
343                                                    NA
344                                                    NA
345                                                    NA
346                                                    NA
347                                                    NA
348                                                    NA
349                                                    NA
350                                                    NA
351                                                    NA
352                                                    NA
357                                                    NA
370                                         MANOHAR NAGAR
374                                                    NA
375                                                    NA
376                                                    NA
377                                                    NA
378                                 Vatika Sovereign Next
379                                                    NA
380                                                    NA
381                                                    NA
382                                                    NA
383                                                    NA
384                                                    NA
385                                                    NA
386                                                    NA
387                                                    NA
388                                                    NA
389                                                    NA
390                                                    NA
391                                                    NA
392                                                    NA
393                                         Sector 14 RWA
394                               IFFCO Nagar and 17B RWA
395                                                    NA
396                                                    NA
397                          Ansal Sushant Lok Plots4.1 ★
398                                                    NA
399                                       Bhim Garh Kheri
400                                                    NA
401                                                    NA
402                                                    NA
403                                                    NA
404                                                    NA
405                        Surendra Homes Dayanand Colony
406                                                    NA
407                                                    NA
408                                                    NA
409                                         DLF The Grove
410                                                    NA
411                                                    NA
412                                                    NA
413                                             RK Excelo
414                                                    NA
415                                                    NA
416                                                    NA
417                                                    NA
419                                                    NA
420                                    Vipul Tatvam Villa
421                              Anand Garden, Sector-105
422                                                    NA
423                                                    NA
424                                                    NA
425                                                    NA
426                                                    NA
427                                Ansal API Esencia3.7 ★
428                                     Anant Raj Estates
429                                                    NA
430                                                    NA
431                                                    NA
432                                                    NA
433                                                    NA
434                                                    NA
435                                                    NA
436                                                    NA
437                                    Jacobpura Gurugram
438                                                    NA
439                                                    NA
440                                            Hero Homes
441                             Ganpati Heights Apartment
442                   International City by Sobha Phase 1
443                                                    NA
444                                                    NA
445                                  Housing Board Colony
446                                      Smart World Gems
447                                                    NA
448                                        Unitech Espace
449                                                    NA
450                                        Not Applicable

In [132]:
#Removing words with different
df['society']=df['society'].str.replace(r'\d+(\.\d+)?\s?★',"",regex = True).str.lower()

In [133]:
df.head(2)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,na,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322

In [134]:
df = df[df['price']!='Price on Request']

In [135]:
def treat_price(x):
  if x[1]=='Lac':
    return round(float(x[0])/100,2)
  else:
    return round(float(x[0]))

In [136]:
df['price'] = df['price'].str.split().apply(treat_price)

In [137]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.0,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,na,6.0,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,na,2.0,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,na,5.0,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,na,3.0,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [138]:
df.rename(columns = {'rate':'price_per_sqft'},inplace=True)

In [139]:
df['price_per_sqft']=df['price_per_sqft'].str.split().str[1].str.split('/').str[0].str.replace(',','').astype('float')

In [140]:
df['bedRoom']=df['bedRoom'].str.split().str[0].astype('int')

In [143]:
df['bathroom']=df['bathroom'].str.split().str[0].astype('int')

In [144]:
df['balcony']=df['balcony'].str.split().str[0]

In [146]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [147]:
df['additionalRoom'].fillna('not available',inplace=True)

/tmp/ipykernel_2133/1615843200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [148]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [150]:
df['noOfFloor'].head()

0    3 Floors
1    2 Floors
2    5 Floors
3    5 Floors
4    5 Floors
Name: noOfFloor, dtype: object

In [151]:
df['noOfFloor'].isnull().sum()

np.int64(19)

In [153]:
df['noOfFloor']=df['noOfFloor'].str.split().str[0]

In [154]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.0,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,na,6.0,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,na,2.0,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,na,5.0,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,na,3.0,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [155]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [156]:
df['facing'].fillna('NA',inplace=True)

/tmp/ipykernel_2133/3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [157]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [158]:
df.insert(loc=1,column='property_type',value='house')

In [159]:
df.to_csv('house_cleaned.csv',index=False)