In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/gurgaon_properties.csv")

In [7]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,...,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Sector 63A Gurgaon,flat,signature global city 63a,1.55,14783.0,1049.0,Carpet area: 1050 (97.55 sq.m.),2,2,2,...,"Sector 63A Gurgaon, Gurgaon, Haryana",2.0,NaN,By 2024,"['Sector 54 Chowk Metro Station', 'Paras Trini...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",S70013926
1,4 BHK Flat in Sector 90 Gurgaon,flat,dlf new town heights,1.75,5720.0,3059.0,Super Built up area 2727(253.35 sq.m.),4,4,3+,...,"Middle Floor, Park Facing, Sector 90 Gurgaon, ...",17.0,South,1 to 5 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",4 bhk with servant room flat for sale\nMany mo...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of...",H42579745
2,3 BHK Flat in Sector 37D Gurgaon,flat,ramprastha primera,1.02,6000.0,1700.0,Super Built up area 1700(157.94 sq.m.),3,2,3,...,"Sector 37D Gurgaon, Gurgaon, Haryana",22.0,NaN,Under Construction,"['JMS Marine Square Mall', 'HUDA Market', 'Dwa...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",Q67217474
3,2 BHK Flat in Sector 3 Gurgaon,flat,godrej habitat,1.30,9002.0,1444.0,Carpet area: 1444 (134.15 sq.m.),2,2,2,...,"Sector 3 Gurgaon, Gurgaon, Haryana",6.0,NaN,By 2024,"['Huda City Centre Metro Station', 'Star Mall'...",Flat is available in premium tower,"['1 Stove', '1 Modular Kitchen', '1 Chimney', ...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4.5 out of 5', 'Lifestyle4 out of...",A70090900
4,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,1.30,10483.0,1240.0,Super Built up area 1772(164.62 sq.m.)Carpet a...,2,2,3+,...,"Tower 2, Sector 85 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Situated in sector 85 gurgaon, ss the leaf is ...","['10 Light', '4 AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou...",S69963366

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3941 entries, 0 to 3940
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3941 non-null   object
 1   property_type    3941 non-null   object
 2   society          3940 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3941 non-null   object
 7   bedRoom          3941 non-null   int64
 8   bathroom         3941 non-null   int64
 9   balcony          3941 non-null   object
 10  additionalRoom   3941 non-null   object
 11  address          3930 non-null   object
 12  floorNum         3920 non-null   float64
 13  facing           2770 non-null   object
 14  agePossession    3940 non-null   object
 15  nearbyLocations  3735 non-null   object
 16  description      3941 non-null   object
 17  furnishDetails   2915 non-null   object
 18  features         3236 non-null   object
 19  rating           3493 non-null   object
 20  property_id      3941 non-null   object
dtypes: float64(4), int64(2), object(15)
memory usage: 646.7+ KB

In [5]:
df.isna().sum(df)

property_name         0
property_type         0
society               1
price                 0
price_per_sqft        0
area                  0
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1171
agePossession         1
nearbyLocations     206
description           0
furnishDetails     1026
features            705
rating              448
property_id           0
dtype: int64

In [6]:
df.shape

(3941, 21)

In [9]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.insert(loc = 3 ,column = 'sector', value = df['property_name'].str.split('in').str[1].str.replace('Gurgaon','').str.strip())

In [17]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Sector 63A Gurgaon,flat,signature global city 63a,Sector 63A,1.55,14783.0,1049.0,Carpet area: 1050 (97.55 sq.m.),2,2,2,not available,"Sector 63A Gurgaon, Gurgaon, Haryana",2.0,NaN,By 2024,"['Sector 54 Chowk Metro Station', 'Paras Trini...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",S70013926
1,4 BHK Flat in Sector 90 Gurgaon,flat,dlf new town heights,Sector 90,1.75,5720.0,3059.0,Super Built up area 2727(253.35 sq.m.),4,4,3+,"pooja room,servant room","Middle Floor, Park Facing, Sector 90 Gurgaon, ...",17.0,South,1 to 5 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",4 bhk with servant room flat for sale\nMany mo...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of...",H42579745
2,3 BHK Flat in Sector 37D Gurgaon,flat,ramprastha primera,Sector 37D,1.02,6000.0,1700.0,Super Built up area 1700(157.94 sq.m.),3,2,3,not available,"Sector 37D Gurgaon, Gurgaon, Haryana",22.0,NaN,Under Construction,"['JMS Marine Square Mall', 'HUDA Market', 'Dwa...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...",Q67217474
3,2 BHK Flat in Sector 3 Gurgaon,flat,godrej habitat,Sector 3,1.30,9002.0,1444.0,Carpet area: 1444 (134.15 sq.m.),2,2,2,not available,"Sector 3 Gurgaon, Gurgaon, Haryana",6.0,NaN,By 2024,"['Huda City Centre Metro Station', 'Star Mall'...",Flat is available in premium tower,"['1 Stove', '1 Modular Kitchen', '1 Chimney', ...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4.5 out of 5', 'Lifestyle4 out of...",A70090900
4,2 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,Sector 85,1.30,10483.0,1240.0,Super Built up area 1772(164.62 sq.m.)Carpet a...,2,2,3+,store room,"Tower 2, Sector 85 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Situated in sector 85 gurgaon, ss the leaf is ...","['10 Light', '4 AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou...",S69963366

In [18]:
df['sector'] = df['sector'].str.lower()

In [19]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [24]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [25]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

/tmp/ipykernel_389/901147752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
/tmp/ipykernel_389/901147752.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
/tmp/ipykernel_389/901147752.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
/tmp/ipykernel_389/901147752.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
/tmp/ipykernel_389/901147752.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
/tmp/ipykernel_389/901147752.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
/tmp/ipykernel_389/901147752.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
/tmp/ipykernel_389/901147752.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
/tmp/ipykernel_389/901147752.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
/tmp/ipykernel_389/901147752.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
/tmp/ipykernel_389/901147752.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
/tmp/ipykernel_389/901147752.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
/tmp/ipykernel_389/901147752.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
/tmp/ipykernel_389/901147752.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
/tmp/ipykernel_389/901147752.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
/tmp/ipykernel_389/901147752.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
/tmp/ipykernel_389/901147752.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [27]:
df.shape

(3785, 22)

In [28]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

/tmp/ipykernel_389/1872267401.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [29]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,property_id
0,flat,signature global city 63a,sector 63a,1.55,14783.0,1049.0,Carpet area: 1050 (97.55 sq.m.),2,2,2,not available,2.0,NaN,By 2024,"['Sector 54 Chowk Metro Station', 'Paras Trini...",NaN,NaN,S70013926
1,flat,dlf new town heights,sector 90,1.75,5720.0,3059.0,Super Built up area 2727(253.35 sq.m.),4,4,3+,"pooja room,servant room",17.0,South,1 to 5 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",H42579745
2,flat,ramprastha primera,sector 37d,1.02,6000.0,1700.0,Super Built up area 1700(157.94 sq.m.),3,2,3,not available,22.0,NaN,Under Construction,"['JMS Marine Square Mall', 'HUDA Market', 'Dwa...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...",Q67217474
3,flat,godrej habitat,sector 3,1.30,9002.0,1444.0,Carpet area: 1444 (134.15 sq.m.),2,2,2,not available,6.0,NaN,By 2024,"['Huda City Centre Metro Station', 'Star Mall'...","['1 Stove', '1 Modular Kitchen', '1 Chimney', ...","['Power Back-up', 'Feng Shui / Vaastu Complian...",A70090900
4,flat,ss the leaf,sector 85,1.30,10483.0,1240.0,Super Built up area 1772(164.62 sq.m.)Carpet a...,2,2,3+,store room,10.0,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","['10 Light', '4 AC', 'No Bed', 'No Chimney', '...","['Centrally Air Conditioned', 'Water purifier'...",S69963366

In [30]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)